// SPDX-License-Identifier: Apache-2.0
// bus/bus.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bus/bus.proto

package bus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	StartNano     uint64                 `protobuf:"varint,6,opt,name=start_nano,json=startNano,proto3" json:"start_nano,omitempty"`
	EndNano       uint64                 `protobuf:"varint,7,opt,name=end_nano,json=endNano,proto3" json:"end_nano,omitempty"`
	StatusCode    string                 `protobuf:"bytes,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,9,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceAttrs map[string]string      `protobuf:"bytes,10,rep,name=resource_attrs,json=resourceAttrs,proto3" json:"resource_attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_bus_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_bus_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_bus_bus_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Span) GetStartNano() uint64 {
	if x != nil {
		return x.StartNano
	}
	return 0
}

func (x *Span) GetEndNano() uint64 {
	if x != nil {
		return x.EndNano
	}
	return 0
}

func (x *Span) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Span) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Span) GetResourceAttrs() map[string]string {
	if x != nil {
		return x.ResourceAttrs
	}
	return nil
}

type AssembledTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Spans         []*Span                `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssembledTrace) Reset() {
	*x = AssembledTrace{}
	mi := &file_bus_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssembledTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssembledTrace) ProtoMessage() {}

func (x *AssembledTrace) ProtoReflect() protoreflect.Message {
	mi := &file_bus_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssembledTrace.ProtoReflect.Descriptor instead.
func (*AssembledTrace) Descriptor() ([]byte, []int) {
	return file_bus_bus_proto_rawDescGZIP(), []int{1}
}

func (x *AssembledTrace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AssembledTrace) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *AssembledTrace) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

// CanonicalizedTrace pairs a finalized trace with the canonical flow it
// collapsed into: root_hash is the flow id (canonical Merkle root), trace is
// the original timed spans verbatim, and span_node_hashes maps each span_id to
// the hash of the canonical node it produced. Many spans (retries / fan-out)
// may share one node hash — that is the intended structural grouping.
type CanonicalizedTrace struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootHash       string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Trace          *AssembledTrace        `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	SpanNodeHashes map[string]string      `protobuf:"bytes,3,rep,name=span_node_hashes,json=spanNodeHashes,proto3" json:"span_node_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CanonicalizedTrace) Reset() {
	*x = CanonicalizedTrace{}
	mi := &file_bus_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalizedTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalizedTrace) ProtoMessage() {}

func (x *CanonicalizedTrace) ProtoReflect() protoreflect.Message {
	mi := &file_bus_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalizedTrace.ProtoReflect.Descriptor instead.
func (*CanonicalizedTrace) Descriptor() ([]byte, []int) {
	return file_bus_bus_proto_rawDescGZIP(), []int{2}
}

func (x *CanonicalizedTrace) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *CanonicalizedTrace) GetTrace() *AssembledTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CanonicalizedTrace) GetSpanNodeHashes() map[string]string {
	if x != nil {
		return x.SpanNodeHashes
	}
	return nil
}

var File_bus_bus_proto protoreflect.FileDescriptor

const file_bus_bus_proto_rawDesc = "" +
	"\n" +
	"\rbus/bus.proto\x12\x03bus\"\xc7\x03\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"start_nano\x18\x06 \x01(\x04R\tstartNano\x12\x19\n" +
	"\bend_nano\x18\a \x01(\x04R\aendNano\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\tR\n" +
	"statusCode\x12*\n" +
	"\x05attrs\x18\t \x03(\v2\x14.bus.Span.AttrsEntryR\x05attrs\x12C\n" +
	"\x0eresource_attrs\x18\n" +
	" \x03(\v2\x1c.bus.Span.ResourceAttrsEntryR\rresourceAttrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ResourceAttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0eAssembledTrace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1f\n" +
	"\x05spans\x18\x02 \x03(\v2\t.bus.SpanR\x05spans\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\"\xf6\x01\n" +
	"\x12CanonicalizedTrace\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\x12)\n" +
	"\x05trace\x18\x02 \x01(\v2\x13.bus.AssembledTraceR\x05trace\x12U\n" +
	"\x10span_node_hashes\x18\x03 \x03(\v2+.bus.CanonicalizedTrace.SpanNodeHashesEntryR\x0espanNodeHashes\x1aA\n" +
	"\x13SpanNodeHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B*Z(github.com/arrca-ai/otel-hub-commons/busb\x06proto3"

var (
	file_bus_bus_proto_rawDescOnce sync.Once
	file_bus_bus_proto_rawDescData []byte
)

func file_bus_bus_proto_rawDescGZIP() []byte {
	file_bus_bus_proto_rawDescOnce.Do(func() {
		file_bus_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bus_bus_proto_rawDesc), len(file_bus_bus_proto_rawDesc)))
	})
	return file_bus_bus_proto_rawDescData
}

var file_bus_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bus_bus_proto_goTypes = []any{
	(*Span)(nil),               // 0: bus.Span
	(*AssembledTrace)(nil),     // 1: bus.AssembledTrace
	(*CanonicalizedTrace)(nil), // 2: bus.CanonicalizedTrace
	nil,                        // 3: bus.Span.AttrsEntry
	nil,                        // 4: bus.Span.ResourceAttrsEntry
	nil,                        // 5: bus.CanonicalizedTrace.SpanNodeHashesEntry
}
var file_bus_bus_proto_depIdxs = []int32{
	3, // 0: bus.Span.attrs:type_name -> bus.Span.AttrsEntry
	4, // 1: bus.Span.resource_attrs:type_name -> bus.Span.ResourceAttrsEntry
	0, // 2: bus.AssembledTrace.spans:type_name -> bus.Span
	1, // 3: bus.CanonicalizedTrace.trace:type_name -> bus.AssembledTrace
	5, // 4: bus.CanonicalizedTrace.span_node_hashes:type_name -> bus.CanonicalizedTrace.SpanNodeHashesEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bus_bus_proto_init() }
func file_bus_bus_proto_init() {
	if File_bus_bus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bus_bus_proto_rawDesc), len(file_bus_bus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bus_bus_proto_goTypes,
		DependencyIndexes: file_bus_bus_proto_depIdxs,
		MessageInfos:      file_bus_bus_proto_msgTypes,
	}.Build()
	File_bus_bus_proto = out.File
	file_bus_bus_proto_goTypes = nil
	file_bus_bus_proto_depIdxs = nil
}
